### ISSUE TITLE
请问首页显示的规则是什么？

### ISSUE THREAD

**Issue by firstbyj** [hitchao/Javedio-2.0#5]
能不能自主定义首页显示，比如按添加日期、出品年份排序或者厂牌

**Comment by firstbyj** [comment]
我在论坛上看到了

**Comment by hitchao** [comment]
可以~，鼠标移到右上角就会显示


 
---原始邮件---
发件人: "firstbyj"<notifications@github.com&gt;
发送时间: 2020年1月7日(星期二) 晚上11:15
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hitchao/Javedio-2.0] 请问首页显示的规则是什么？ (#5)



能不能自主定义首页显示，比如按添加日期、出品年份排序或者厂牌
